# .travis.yaml

language: python

sudo: true

env:
  - LUA_VERSION="5.4" KONG_VERSION="1.4.0-0" LUA_RESTY_OPENIDC_VERSION="1.7.2-1"
  - LUA_VERSION="5.4" KONG_VERSION="1.3.0-0" LUA_RESTY_OPENIDC_VERSION="1.7.2-1"
  - LUA_VERSION="5.4" KONG_VERSION="1.2.2-0" LUA_RESTY_OPENIDC_VERSION="1.7.2-1"
  - LUA_VERSION="5.4" KONG_VERSION="1.0.2-0" LUA_RESTY_OPENIDC_VERSION="1.7.2-1"

script:
  - sudo -E bash ci/root.sh
  - . ci/setup.sh
  - . ci/run.sh

after_success:
  - luarocks install luacov-coveralls
  - EXCLUDE_DIR=`echo $TRAVIS_BUILD_DIR/lua_install | sed 's/-/%-/'`
  - luacov-coveralls -e $EXCLUDE_DIR

