# .travis.yaml

language: python

sudo: true

env:
  - LUA_VERSION="5.1" KONG_VERSION="1.4.0-0" LUA_RESTY_OPENIDC_VERSION="1.6.1-1"
  - LUA_VERSION="5.1" KONG_VERSION="1.3.0-0" LUA_RESTY_OPENIDC_VERSION="1.6.1-1"
  - LUA_VERSION="5.1" KONG_VERSION="1.0.2-0" LUA_RESTY_OPENIDC_VERSION="1.6.1-1"

script:
  - sudo -E bash ci/root.sh
  - . ci/setup.sh
  - . ci/run.sh

after_success:
  - docker build -t alaksmana/kong-oidc:0.0.2 .
  - bash ./docker_push
  
#   - luarocks install luacov-coveralls
#   - luacov-coveralls

